name: "bulk-resume-parser"

secrets:
  BETTER_AUTH_SECRET:
    file: .secret

volumes:
  redis-data:
  minio-data:
  app-db-data:

services:
  rabbitmq:
    image: rabbitmq:management
    networks:
      - bulk-resume-parser
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:latest
    restart: always
    networks:
      - bulk-resume-parser
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    networks:
      - bulk-resume-parser
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  extract-archive:
    image: yash6370/extract-archive-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  conversion-director:
    image: yash6370/conversion-director:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  pdf-to-txt:
    image: yash6370/pdf-to-txt-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  img-to-txt:
    image: yash6370/img-to-txt-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  txt-to-json:
    image: yash6370/txt-to-json-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  aggregate-json:
    image: yash6370/aggregate-json-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started

  json-to-sheet:
    image: yash6370/json-to-sheet-service:latest
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  unoserver:
    image: ghcr.io/unoconv/unoserver-docker
    networks:
      - bulk-resume-parser
    ports:
      - "2003:2003"
    restart: unless-stopped

  app:
    image: yash6370/bulk-resume-parser:latest
    networks:
      - bulk-resume-parser
    ports:
      - "3000:3000"

  app-db:
    image: mysql:latest
    networks:
      - bulk-resume-parser
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - app-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin --user=root --password=${DB_ROOT_PASSWORD} --host=localhost --port=3306 ping",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app-db-migrator:
    image: yash6370/app-db-migrator:latest
    networks:
      - bulk-resume-parser
    depends_on:
      app-db:
        condition: service_healthy
    restart: on-failure

networks:
  bulk-resume-parser:
    name: bulk-resume-parser
