services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - bulk-resume-parser
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - bulk-resume-parser
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  extract-archive:
    build:
      context: ./services/extract-archive
    image: extract-archive-service:latest
    container_name: extract-archive
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  word-to-txt:
    build:
      context: ./services/word-to-txt
    image: word-to-txt-service:latest
    container_name: word-to-txt
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  pdf-to-txt:
    build:
      context: ./services/pdf-to-txt
    image: pdf-to-txt-service:latest
    container_name: pdf-to-txt
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  img-to-txt:
    build:
      context: ./services/img-to-txt
    image: img-to-txt-service:latest
    container_name: img-to-txt
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  txt-to-json:
    build:
      context: ./services/txt-to-json
    image: txt-to-json-service:latest
    container_name: txt-to-json
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  json-to-sheet:
    build:
      context: ./services/json-to-sheet
    image: json-to-sheet-service:latest
    container_name: json-to-sheet
    networks:
      - bulk-resume-parser
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      RABBITMQ_HOST: "${RABBITMQ_HOST}"
      RABBITMQ_PORT: "${RABBITMQ_PORT}"
      RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build:
      context: .
      args:
        S3_HOST: "${S3_HOST}"
        S3_PORT: "${S3_PORT}"
        S3_USE_SSL: "${S3_USE_SSL}"
        S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
        S3_SECRET_KEY: "${S3_SECRET_KEY}"
        DATABASE_URL: "${DATABASE_URL}"
        RABBITMQ_URL: "${RABBITMQ_URL}"
        BETTER_AUTH_URL: "${BETTER_AUTH_URL}"
        BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
        NEXT_PUBLIC_BETTER_AUTH_URL: "${NEXT_PUBLIC_BETTER_AUTH_URL}"
    image: bulk-resume-parser:latest
    container_name: app
    networks:
      - bulk-resume-parser
    ports:
      - "3000:3000"
    environment:
      S3_HOST: "${S3_HOST}"
      S3_PORT: "${S3_PORT}"
      S3_USE_SSL: "${S3_USE_SSL}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      DATABASE_URL: "${DATABASE_URL}"
      RABBITMQ_URL: "${RABBITMQ_URL}"
      BETTER_AUTH_URL: "${BETTER_AUTH_URL}"
      BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
      NEXT_PUBLIC_BETTER_AUTH_URL: "${NEXT_PUBLIC_BETTER_AUTH_URL}"

  app-db:
    image: mysql:latest
    container_name: app-db
    networks:
      - bulk-resume-parser
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin --user=root --password=${DB_ROOT_PASSWORD} --host=localhost --port=3306 ping",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app-db-migrator:
    build:
      context: .
      dockerfile: db-migrator.Dockerfile
    container_name: app-db-migrator
    networks:
      - bulk-resume-parser
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      app-db:
        condition: service_healthy
    restart: on-failure

networks:
  bulk-resume-parser:
    name: bulk-resume-parser

volumes:
  redis-data:
  minio-data:
