[project]
name = "word-to-txt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "minio>=7.2.15",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.0",
    "unoserver>=3.2",
]
